### ISSUE TITLE
Information update

### ISSUE THREAD

**Issue by weiyithu** [chaytonmin/Awesome-Occupancy-Prediction-Multi-Cameras#2]
Hi, thanks for your summary. Can you update the name (SurroundOcc: Multi-Camera 3D Occupancy Prediction for Autonomous Driving) and paper link (https://arxiv.org/abs/2303.09551) of SurroundOcc?

**Comment by chaytonmin** [comment]
> Hi, thanks for your summary. Can you update the name (SurroundOcc: Multi-Camera 3D Occupancy Prediction for Autonomous Driving) and paper link (https://arxiv.org/abs/2303.09551) of SurroundOcc?

ok
